# Generated by Django 5.2.15 on 2026-06-23 03:15

import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Este nombre de usuario ya está en uso.'}, help_text='Mínimo 3 caracteres, solo letras, números, puntos, guiones y guiones bajos.', max_length=150, unique=True, validators=[usuarios.models.validar_username])),
                ('email', models.EmailField(error_messages={'unique': 'Este correo electrónico ya está registrado.'}, help_text='Ingresa un correo electrónico válido.', max_length=254, unique=True, validators=[usuarios.models.validar_email])),
                ('first_name', models.CharField(help_text='Mínimo 2 caracteres.', max_length=150, validators=[django.core.validators.MinLengthValidator(2, message='El nombre debe tener al menos 2 caracteres.')])),
                ('last_name', models.CharField(help_text='Mínimo 2 caracteres.', max_length=150, validators=[django.core.validators.MinLengthValidator(2, message='El apellido debe tener al menos 2 caracteres.')])),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('almacenista', 'Almacenista'), ('consultor', 'Consultor')], default='almacenista', help_text='Rol del usuario en el sistema.', max_length=20)),
                ('telefono', models.CharField(blank=True, help_text='Formato: solo números, guiones y paréntesis (mínimo 7 dígitos).', max_length=15, null=True, validators=[usuarios.models.validar_telefono])),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SeguridadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, help_text='Nombre de usuario (si está disponible)', max_length=150, null=True)),
                ('ip', models.GenericIPAddressField(help_text='Dirección IP del usuario')),
                ('accion', models.CharField(choices=[('login_fallo', 'Intento de login fallido'), ('login_exito', 'Login exitoso'), ('logout', 'Logout'), ('intento_bruteforce', 'Ataque de fuerza bruta detectado'), ('cambio_password', 'Cambio de contraseña'), ('acceso_denegado', 'Acceso denegado'), ('intento_admin', 'Intento de acceso a área admin sin permisos'), ('usuario_creado', 'Usuario creado'), ('usuario_eliminado', 'Usuario eliminado'), ('usuario_editado', 'Usuario editado')], help_text='Tipo de evento de seguridad', max_length=30)),
                ('detalles', models.TextField(blank=True, help_text='Detalles adicionales del evento', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Navegador y sistema operativo del usuario', max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del evento')),
            ],
            options={
                'verbose_name': 'Log de Seguridad',
                'verbose_name_plural': 'Logs de Seguridad',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='usuarios_se_fecha_40e980_idx'), models.Index(fields=['ip'], name='usuarios_se_ip_1ce575_idx'), models.Index(fields=['accion'], name='usuarios_se_accion_bbfe6b_idx')],
            },
        ),
    ]
