# Generated by Django 6.0.2 on 2026-05-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguridadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=150, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('accion', models.CharField(choices=[('login_fallo', 'Intento de login fallido'), ('login_exito', 'Login exitoso'), ('logout', 'Logout'), ('intento_bruteforce', 'Ataque de fuerza bruta detectado'), ('cambio_password', 'Cambio de contraseña'), ('acceso_denegado', 'Acceso denegado')], max_length=30)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Seguridad',
                'verbose_name_plural': 'Logs de Seguridad',
                'ordering': ['-fecha'],
            },
        ),
    ]
