# Generated by Django 6.0.2 on 2026-05-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodega',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logactividad',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lote',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productoconserial',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={},
        ),
        migrations.AlterField(
            model_name='producto',
            name='garantia_meses',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
    ]
