# Generated by Django 5.2.15 on 2026-06-23

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'), # Apesta al archivo inicial que me mostraste antes
    ]

    operations = [
        # 1. Por si acaso, eliminamos la columna vieja si existe como texto plano
        migrations.RunSQL(
            sql='ALTER TABLE "Productos_producto" DROP COLUMN IF EXISTS ubicacion;',
            reverse_sql='SELECT 1;'
        ),
        # 2. Creamos la relación ForeignKey real (ubicacion_id)
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='productos', 
                to='Productos.ubicacion',
                help_text='Selecciona una ubicación predefinida'
            ),
        ),
    ]