# Generated by Django 6.0.2 on 2026-05-28 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_bodega_options_alter_logactividad_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoconserial',
            options={'ordering': ['serial']},
        ),
        migrations.AddField(
            model_name='lote',
            name='cantidad_recibida',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lote',
            name='cantidad_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lote',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lote',
            name='fecha_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='Productos.producto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoconserial',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productoconserial',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='estado',
            field=models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('parcial', '📦 Recibido Parcial'), ('completado', '✅ Completado'), ('cancelado', '❌ Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fecha_pedido',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productoconserial',
            name='estado',
            field=models.CharField(choices=[('disponible', '✅ Disponible'), ('vendido', '💰 Vendido'), ('danado', '⚠️ Dañado'), ('devuelto', '🔄 Devuelto'), ('reservado', '📌 Reservado')], default='disponible', max_length=20),
        ),
        migrations.CreateModel(
            name='RecepcionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('seriales', models.TextField(help_text='Lista de seriales recibidos (uno por línea)')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='Productos.lote')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
