# Generated by Django 5.2.15 on 2026-06-23

from django.db import migrations, models
import django.core.validators

class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20260623_0718'), # Enlaza directamente con la migración anterior
    ]

    operations = [
        # 1. Por si acaso, eliminamos la columna vieja si existe con otro formato
        migrations.RunSQL(
            sql='ALTER TABLE "Productos_lote" DROP COLUMN IF EXISTS cantidad_vendida;',
            reverse_sql='SELECT 1;'
        ),
        # 2. Inyectamos la columna 'cantidad_vendida' con las propiedades de tu modelo original
        migrations.AddField(
            model_name='lote',
            name='cantidad_vendida',
            field=models.IntegerField(
                default=0, 
                validators=[django.core.validators.MinValueValidator(0, 'La cantidad vendida no puede ser negativa')]
            ),
        ),
    ]